export const GET_DATA_REQUEST = 'GET_DATA_REQUEST'
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS'
export const GET_DATA_ERROR = 'GET_DATA_ERROR'

export const CLOSE_HEADR = 'CLOSE_HEADER'

export const VIDEO_PREPARE = 'VIDEO_PREPARE'
export const VIDEO_READY = 'VIDEO_READY'
